"""Central configuration for agent orchestration."""

DEFAULT_FEEDBACK_MAX_RETRIES = 2
DEEPSEEK_BASE_URL = "https://api.deepseek.com"
DEEPSEEK_MODEL = "deepseek-v4-flash"
SPECIALIST_MAX_TOKENS = 3000
SKEPTIC_MAX_TOKENS = 5000
FINAL_AGENT_MAX_TOKENS = 10000
SEARCH_TOP_K = 2
SEARCH_MAX_EXCERPTS_PER_RESULT = 2
SEARCH_MAX_EXCERPT_CHARS = 400
